version: '2'
services:
  web:
    build: .
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    container_name: elasticsearch_web
    depends_on:
      - db
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    volumes_from:
      - bundle
  db:
    image: postgres
  elasticsearch:
    entrypoint: /entrypoints/elasticsearch.sh
    image: elasticsearch
    ports:
      - 9200:9200
    volumes:
      - ./entrypoints:/entrypoints
  kibana:
    image: kibana
    links:
      - elasticsearch
    ports:
      - 5601:5601
  bundle:
    image: busybox
    volumes:
      - /bundle
