version: '2'
services:
  web:
    build: .
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    container_name: elasticsearch_web
    depends_on:
      - db
      - elasticsearch
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    volumes_from:
      - bundle
  db:
    image: postgres
  elasticsearch:
    image: elasticsearch
    ports:
      - 9200:9200
  bundle:
    image: busybox
    volumes:
      - /bundle
